url: https://y7kim.github.io
baseurl: ""

# Site settings
title: datavisyn
email: contact@datavisyn.io
description: "We develop data visualization solutions for applications in pharmaceutical and biomedical R&D."


# Team names, titles and social links
people:
- name: Marc Streit
  pic: streit
  position: CEO and Co-Founder
  affiliation:
    title: Professor at Johannes Kepler University Linz
    url: https://www.jku.at/en/institute-of-computer-graphics/
  social:
    - title: home
      url: http://marc-streit.com
    - title: twitter
      url: http://twitter.com/marc_streit
    - title: linkedin
      url: http://www.linkedin.com/in/marcstreit

- name: Samuel Gratzl
  pic: gratzl
  position: CTO and Co-Founder

- name: Alexander Lex
  pic: lex
  position: Co-Founder
  affiliation:
    title: Professor at University of Utah
    url: http://vdl.sci.utah.edu/team/lex/
  social:
    - title: home
      url: http://alexander-lex.com
    - title: twitter
      url: http://twitter.com/alexander_lex
    - title: linkedin
      url: https://www.linkedin.com/in/alexander-lex-83961533

- name: Nils Gehlenborg
  pic: gehlenborg
  position: Co-Founder
  affiliation:
    title: Professor at Harvard Medial School
    url: http://gehlenborglab.org/
  social:
    - title: home
      url: http://gehlenborglab.org/
    - title: twitter
      url: http://twitter.com/nils_gehlenborg
    - title: linkedin
      url: http://www.linkedin.com/in/ngehlenborg

- name: Christian Lehner
  pic: lehner
  position: Full Stack Developer
  social:
    - title: twitter
      url: https://twitter.com/chri_lehner
    - title: linkedin
      url: https://www.linkedin.com/in/christianlehner

- name: Stefan Luger
  pic: luger
  position: Full Stack Developer
  social:
    - title: twitter
      url: https://twitter.com/Stefan_Luxi
    - title: linkedin
      url: https://at.linkedin.com/in/stefanluger


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/datavisyn
  - title: github
    url: http://github.com/datavisyn

# Postal address (add as many lines as necessary)
address:
  - line: Weingartshofstraße 27 1.2
  - line: 4020 Linz, Austria

collections:
  - platform
  - products
  - services
  - customers

partner:
  shortname: JKU Linz
  name: Johannes Kepler University Linz
supporter:
  name: tech2b
  url: http://tech2b.at

# Build settings
markdown: kramdown
permalink: pretty
