url: https://y7kim.github.io
baseurl: ""

# Site settings
title: datavisyn
email: contact@datavisyn.io
description: "We develop data visualization solutions for applications in pharmaceutical and biomedical R&D."


# Team names, titles and social links
people:
- name: Marc Streit
  pic: streit
  position: CEO and Co-Founder
  social:
    - title: home
      url: http://marc-streit.com
    - title: twitter
      url: http://twitter.com/marc_streit
    - title: linkedin
      url: http://www.linkedin.com/in/marcstreit

- name: Samuel Gratzl
  pic: gratzl
  position: CTO and Co-Founder

- name: Alexander Lex
  pic: lex
  position: Co-Founder
  social:
    - title: home
      url: http://alexander-lex.com
    - title: twitter
      url: http://twitter.com/alexander_lex
    - title: linkedin
      url: https://www.linkedin.com/in/alexander-lex-83961533

- name: Nils Gehlenborg
  pic: gehlenborg
  position: Co-Founder
  social:
    - title: twitter
      url: http://twitter.com/nils_gehlenborg
    - title: linkedin
      url: http://www.linkedin.com/in/ngehlenborg

- name: Christian Lehner
  pic: lehner
  position: Developer
  social:
    - title: twitter
      url: https://twitter.com/chri_lehner
    - title: linkedin
      url: https://www.linkedin.com/in/christianlehner


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/datavisyn
  - title: github
    url: http://github.com/datavisyn

# Postal address (add as many lines as necessary)
address:
  - line: Weingartshofstraße 27 1.2
  - line: 4020 Linz, Austria

products:
  - name: Ordino
    description: "Ordino is a platform designed to bring data analysis workflows to the next level. It allows to interactively calculate scores, rank, filter and visualize datasets. Internal and external detail views are seamlessly integrated in Ordino to provide all the data and visualizations needed to identify analysis targets."
    link:
      text: Try it yourself
      url: https://ordino-daily.caleydoapp.org
    images:
      - caption:
          header: Ordino Entry
          text: Start from a full dataset
        file: Ordino_1.png
        class: active
      - caption:
          header: Visualizations
          text: Select items (e.g. outliers) in different detail views or get information of external resources
        file: Ordino_2.png
        class: ""
      - caption:
          header: Detail Views & Filter
          text: Open new detail views based on the selected items and filter, add scores, etc.
        file: Ordino_3.png
        class: ""
    features:
      - header: Ranking and scoring
        text: Flexibly rank and filter entities such as genes, cell lines, and tissues based on preloaded data, dynamically aggregated data, or additional meta-data
        iconClass: sort-amount-desc
      - header: Innovative visualizations
        text: We integrate novel visualization techniques developed in the academic groups of the co-founders.
        iconClass: bar-chart
      - header: Sharing and reproducibility
        text: Provenance tracking is where Ordino shines. User can jump back to any state of previous analysis, continue the analysis, or share it with colleagues via the browser URL.
        iconClass: repeat
      - header: Data sources
        text: Load data from in-house databases, load public datasets such as TCGA and CCLE, or upload additional data from files. Your private version of Ordino can be extended to use your own data sources. Interested? Contact us!
        iconClass: database
      - header: Annotations
        text: Flexible mapping mechanism that deals with multi-mapping and various annotations (ENSEMBL, GeneSymbol, etc.)
        iconClass: exchange



# Build settings
markdown: kramdown
permalink: pretty
