url: https://y7kim.github.io
baseurl: ""

# Site settings
title: datavisyn
email: contact@datavisyn.io
description: "We develop data visualization solutions for applications in pharmaceutical and biomedical R&D."


# Team names, titles and social links
people:
- name: Marc Streit
  pic: streit
  position: CEO and Co-Founder
  social:
    - title: home
      url: http://marc-streit.com
    - title: twitter
      url: http://twitter.com/marc_streit
    - title: linkedin
      url: http://www.linkedin.com/in/marcstreit

- name: Samuel Gratzl
  pic: gratzl
  position: CTO and Co-Founder

- name: Alexander Lex
  pic: lex
  position: Co-Founder
  social:
    - title: home
      url: http://alexander-lex.com
    - title: twitter
      url: http://twitter.com/alexander_lex
    - title: linkedin
      url: https://www.linkedin.com/in/alexander-lex-83961533

- name: Nils Gehlenborg
  pic: gehlenborg
  position: Co-Founder
  social:
    - title: twitter
      url: http://twitter.com/nils_gehlenborg
    - title: linkedin
      url: http://www.linkedin.com/in/ngehlenborg

- name: Christian Lehner
  pic: lehner
  position: Developer
  social:
    - title: twitter
      url: https://twitter.com/chri_lehner
    - title: linkedin
      url: https://www.linkedin.com/in/christianlehner


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/datavisyn
  - title: github
    url: http://github.com/datavisyn

# Postal address (add as many lines as necessary)
address:
  - line: Weingartshofstraße 27 1.2
  - line: 4020 Linz, Austria

products:
  - name: Ordino
    description: "Ordino is a platform designed to bring your data analysis workflow to the next level. It allows you to interactively calculate scores, rank, filter and visualize the dataset and with different detail views you find the
information you need. Internal and external detail views are seamlessly integrated in Ordino to provide all the data you need. Furthermore you can share your current work with your colleagues who can continue where you stopped."
    link:
      text: Try it yourself
      url: https://ordino-daily.caleydoapp.org
    images:
      - caption:
          header: Ordino Entry
          text: Start from a full dataset
        file: Ordino_1.png
        class: active
      - caption:
          header: Visualizations
          text: Select items (e.g. outliers) in different detail views or get information of external resources
        file: Ordino_2.png
        class: ""
      - caption:
          header: Detail Views & Filter
          text: Open new detail views based on the selected items and filter, add scores, etc.
        file: Ordino_3.png
        class: ""
    features:
      - header: flexible ranking and scoring features
        text: Dynamically add new score columns directly in Ordino and use them to rank your entities or filter them.
        iconClass: sort-amount-desc
      - header: provenance tracking and reproducibility
        text: Provenance tracking is where Ordino really shines. It allows you to jump back to any point of time in your analysis history and create a new branch.
        iconClass: repeat
      - header: data providers
        text: You need access to a different data source? Your private version of Ordino can be extended to use your own data sources. Interested? Contact us!
        iconClass: database


# Build settings
markdown: kramdown
permalink: pretty
