url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: datavisyn
email: contact@datavisyn.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Marc Streit
  pic: streit
  position: CEO and Co-Founder
  social:
    - title: home
      url: http://marc-streit.com
    - title: twitter
      url: http://twitter.com/marc_streit
    - title: linkedin
      url: http://www.linkedin.com/in/marcstreit

- name: Samuel Gratzl
  pic: gratzl
  position: CTO and Co-Founder
  social:
    - title: home
      url: http://sgratzl.github.io

- name: Alexander Lex
  pic: lex
  position: Co-Founder
  social:
    - title: home
      url: http://alexander-lex.com
    - title: twitter
      url: http://twitter.com/alexander_lex
    - title: linkedin
      url: http://www.linkedin.com/in/alexander-lex

- name: Nils Gehlenborg
  pic: gehlenborg
  position: Co-Founder
  social:
    - title: home
      url: http://gehlenborg.com
    - title: twitter
      url: http://twitter.com/nils_gehlenborg
    - title: linkedin
      url: http://www.linkedin.com/in/ngehlenborg


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/datavisyn
  - title: github
    url: http://github.com/datavisyn

# Postal address (add as many lines as necessary)
address:
  - line: Weingartshofstraße 27 1.2
  - line: 4020 Linz, Austria

# Build settings
markdown: kramdown
permalink: pretty